### 1. Tentar criar um aluno com dados inválidos (Testando a Validação)
POST http://localhost:8080/alunos
Content-Type: application/json

{
  "nome": "",
  "email": "email-invalido",
  "matricula": ""
}

### 2. Criar um aluno com dados corretos (POST)
POST http://localhost:8080/alunos
Content-Type: application/json

{
  "nome": "Rafael Fonseca",
  "email": "rafael@ucpel.edu.br",
  "matricula": "202610123"
}

### 3. Listar todos os alunos (GET)
GET http://localhost:8080/alunos
Accept: application/json

### 4. Atualizar os dados do aluno recém-criado (PUT)
# (Assumindo que o ID gerado pelo banco foi 1)
PUT http://localhost:8080/alunos/1
Content-Type: application/json

{
  "nome": "Rafael Fonseca de Souza",
  "email": "rafael.souza@ucpel.edu.br",
  "matricula": "202610123"
}

### 5. Deletar o aluno (DELETE)
DELETE http://localhost:8080/alunos/1